import "relay/KoLmafia-Guide/Paths/Actually Ed the Undying.ash";
import "relay/KoLmafia-Guide/Paths/Avatar of Jarlsberg.ash";
import "relay/KoLmafia-Guide/Paths/Avatar of Sneaky Pete.ash";
import "relay/KoLmafia-Guide/Paths/Avatar of West of Loathing.ash";
import "relay/KoLmafia-Guide/Paths/Bad Moon.ash";
import "relay/KoLmafia-Guide/Paths/Bugbear Invasion.ash";
import "relay/KoLmafia-Guide/Paths/Community Service.ash";
import "relay/KoLmafia-Guide/Paths/Heavy Rains.ash";
import "relay/KoLmafia-Guide/Paths/KOLHS.ash";
import "relay/KoLmafia-Guide/Paths/Way of the Surprising Fist.ash";
import "relay/KoLmafia-Guide/Paths/The Source.ash";
import "relay/KoLmafia-Guide/Paths/Zombie Slayer.ash";
import "relay/KoLmafia-Guide/Paths/Nuclear Autumn.ash";
import "relay/KoLmafia-Guide/Paths/Gelatinous Noob.ash";
import "relay/KoLmafia-Guide/Paths/License to Adventure.ash";
import "relay/KoLmafia-Guide/Paths/G-Lover.ash";
import "relay/KoLmafia-Guide/Paths/Explosions.ash";
import "relay/KoLmafia-Guide/Paths/Low Key.ash";
import "relay/KoLmafia-Guide/Paths/Quantum of Familiar.ash";

