import "relay/KoLmafia-Guide/Quests/Level 2.ash";
import "relay/KoLmafia-Guide/Quests/Level 3.ash";
import "relay/KoLmafia-Guide/Quests/Level 4.ash";
import "relay/KoLmafia-Guide/Quests/Level 5.ash";
import "relay/KoLmafia-Guide/Quests/Level 6.ash";
import "relay/KoLmafia-Guide/Quests/Level 7.ash";
import "relay/KoLmafia-Guide/Quests/Level 8.ash";
import "relay/KoLmafia-Guide/Quests/Level 9.ash";
import "relay/KoLmafia-Guide/Quests/Level 10.ash";
import "relay/KoLmafia-Guide/Quests/Level 11.ash";
import "relay/KoLmafia-Guide/Quests/Level 12.ash";
import "relay/KoLmafia-Guide/Quests/Level 13.ash";
import "relay/KoLmafia-Guide/Quests/Manor.ash";
import "relay/KoLmafia-Guide/Quests/Pirate.ash";
import "relay/KoLmafia-Guide/Quests/Nemesis.ash";
import "relay/KoLmafia-Guide/Quests/Sea.ash";
import "relay/KoLmafia-Guide/Quests/Space Elves.ash";
import "relay/KoLmafia-Guide/Quests/Azazel.ash";
import "relay/KoLmafia-Guide/Quests/Untinker.ash";
import "relay/KoLmafia-Guide/Quests/Artist.ash";
import "relay/KoLmafia-Guide/Quests/Legendary Beat.ash";
import "relay/KoLmafia-Guide/Quests/Memories.ash";
import "relay/KoLmafia-Guide/Quests/White Citadel.ash";
import "relay/KoLmafia-Guide/Quests/Wizard of Ego.ash";
import "relay/KoLmafia-Guide/Quests/Spookyraven Lights Out.ash";
import "relay/KoLmafia-Guide/Quests/Felonia.ash";
import "relay/KoLmafia-Guide/Quests/Guild.ash";
import "relay/KoLmafia-Guide/Quests/Airport.ash";
import "relay/KoLmafia-Guide/Quests/Subject 37.ash";
import "relay/KoLmafia-Guide/Quests/Marty.ash";
import "relay/KoLmafia-Guide/Quests/Meatsmith.ash";
import "relay/KoLmafia-Guide/Quests/Intergalaktik.ash";
import "relay/KoLmafia-Guide/Quests/Old Landfill.ash";
import "relay/KoLmafia-Guide/Quests/Madness Bakery.ash";

